from collections.abc import Iterator
from contextlib import ExitStack, contextmanager

import httpx
from fastapi.testclient import TestClient

from services.gateway.clients import InferenceClient, NameServiceClient, ReplicaClient
from services.gateway.main import create_app as create_gateway_app
from services.gateway.service import GatewayService
from services.inference_adapter.main import create_app as create_inference_adapter_app
from services.inference_adapter.runtime import InferenceResult, StreamEvent
from services.inference_adapter.service import InferenceService
from services.name_service.main import create_app as create_name_service_app
from services.replica.cache_service import CacheService
from services.replica.clients import ReplicaPeerClient
from services.replica.embedding import DeterministicTestEmbedder
from services.replica.main import create_app as create_replica_app
from services.replica.manager import ReplicaManager
from services.replica.vector_store import VectorStoreAdapter
from shared.config import InferenceAdapterSettings, ReplicaSettings
from tests.replica_fakes import FakeQdrantClient


class NoOpAsyncNameServiceClient:
    async def register(self, payload: dict) -> dict:
        return {"registered": True, "member": payload}

    async def heartbeat(self, payload: dict) -> dict:
        return {"accepted": True, "member": payload}

    async def close(self) -> None:
        return None


class TrackingRuntime:
    def __init__(self, response_text: str = "generated by inference runtime") -> None:
        self.response_text = response_text
        self.started = False
        self.stopped = False
        self.infer_calls = 0
        self.requests: list[dict] = []

    def start(self) -> None:
        self.started = True

    def stop(self) -> None:
        self.stopped = True

    def health(self) -> tuple[str, str]:
        return "ok", "Tracking runtime is ready."

    def infer(self, payload: dict) -> InferenceResult:
        self.infer_calls += 1
        self.requests.append(dict(payload))
        return InferenceResult(
            response_text=self.response_text,
            model_id=payload["model_id"],
            provider="tracking-runtime",
        )

    def stream(self, payload: dict) -> Iterator[StreamEvent]:
        self.infer_calls += 1
        self.requests.append(dict(payload))
        yield StreamEvent(event="token", data=self.response_text)
        yield StreamEvent(
            event="done",
            data=(
                '{"response_text":"%s","model_id":"%s","provider":"tracking-runtime"}'
                % (self.response_text, payload["model_id"])
            ),
        )


def test_gateway_cache_hit_returns_cached_answer_without_inference() -> None:
    with integrated_system() as system:
        seed_response = system.managers["replica-b"].write_cache(
            {
                "prompt": "what is cachemesh",
                "response_text": "a distributed semantic cache",
                "model_id": "demo",
            }
        )

        response = system.gateway.post(
            "/cache/query",
            json={"prompt": "what is cachemesh", "model_id": "demo", "semantic_enabled": True},
        )

    assert seed_response["stored"] is True
    assert response.status_code == 200
    assert response.json()["status"] == "ok"
    assert response.json()["hit"] is True
    assert response.json()["response_text"] == "a distributed semantic cache"
    assert response.json()["cache_status"] == "hit"
    assert system.runtime.infer_calls == 0


def test_gateway_cache_miss_calls_inference_and_replicates_write() -> None:
    with integrated_system() as system:
        response = system.gateway.post(
            "/cache/query",
            json={
                "prompt": "explain distributed caching",
                "model_id": "demo",
                "semantic_enabled": True,
            },
        )
        replica_hits = {
            replica_id: manager.read_cache(
                {
                    "prompt": "explain distributed caching",
                    "model_id": "demo",
                    "semantic_enabled": True,
                }
            )
            for replica_id, manager in system.managers.items()
        }

    assert response.status_code == 200
    assert response.json()["status"] == "ok"
    assert response.json()["hit"] is False
    assert response.json()["response_text"] == "generated by inference runtime"
    assert response.json()["cache_status"] == "miss_generated"
    assert system.runtime.infer_calls == 1
    assert system.runtime.requests == [
        {"prompt": "explain distributed caching", "model_id": "demo"}
    ]
    for hit in replica_hits.values():
        assert hit["hit"] is True
        assert hit["response_text"] == "generated by inference runtime"


class IntegratedSystem:
    def __init__(
        self,
        gateway: TestClient,
        managers: dict[str, ReplicaManager],
        runtime: TrackingRuntime,
    ) -> None:
        self.gateway = gateway
        self.managers = managers
        self.runtime = runtime


@contextmanager
def integrated_system() -> Iterator[IntegratedSystem]:
    import services.gateway.routes as gateway_routes
    import services.name_service.routes as name_service_routes

    name_service_routes.registry.members.clear()
    runtime = TrackingRuntime()
    inference_service = InferenceService(
        settings=InferenceAdapterSettings(inference_backend="stub"),
        runtime=runtime,
    )
    managers = {
        "replica-a": _build_replica_manager(_replica_settings("replica-a", 8201)),
        "replica-b": _build_replica_manager(_replica_settings("replica-b", 8202)),
        "replica-c": _build_replica_manager(_replica_settings("replica-c", 8203)),
    }
    clients_by_origin: dict[str, TestClient] = {}

    def transport_handler(request: httpx.Request) -> httpx.Response:
        origin = _origin(str(request.url))
        client = clients_by_origin[origin]
        path = request.url.path
        if request.url.query:
            path = f"{path}?{request.url.query.decode()}"
        forwarded = client.request(
            request.method,
            path,
            content=request.content,
            headers={key: value for key, value in request.headers.items() if key.lower() != "host"},
        )
        return httpx.Response(
            status_code=forwarded.status_code,
            headers=forwarded.headers,
            content=forwarded.content,
            request=request,
        )

    transport = httpx.MockTransport(transport_handler)

    with ExitStack() as stack:
        name_service_client = stack.enter_context(TestClient(create_name_service_app()))
        inference_client = stack.enter_context(
            TestClient(create_inference_adapter_app(inference_service=inference_service))
        )
        replica_clients = {}
        for replica_id, manager in managers.items():
            manager.peer_client = ReplicaPeerClient(timeout_sec=2.0, transport=transport)
            client = stack.enter_context(TestClient(create_replica_app(replica_manager=manager)))
            replica_clients[replica_id] = client

        clients_by_origin.update(
            {
                "http://name-service:8100": name_service_client,
                "http://inference-adapter:8050": inference_client,
                "http://replica-a:8201": replica_clients["replica-a"],
                "http://replica-b:8202": replica_clients["replica-b"],
                "http://replica-c:8203": replica_clients["replica-c"],
            }
        )

        gateway_service = GatewayService(
            name_service_client=NameServiceClient(
                "http://name-service:8100",
                2.0,
                transport=transport,
            ),
            replica_client=ReplicaClient(2.0, transport=transport),
            inference_client=InferenceClient(
                "http://inference-adapter:8050",
                2.0,
                transport=transport,
            ),
        )
        original_gateway_service = gateway_routes.service
        gateway_routes.service = gateway_service
        stack.callback(setattr, gateway_routes, "service", original_gateway_service)
        gateway_client = stack.enter_context(TestClient(create_gateway_app()))

        for replica_id, port in [("replica-a", 8201), ("replica-b", 8202), ("replica-c", 8203)]:
            register = name_service_client.post(
                "/register",
                json={"replica_id": replica_id, "host": replica_id, "port": port},
            )
            assert register.status_code == 200

        yield IntegratedSystem(gateway=gateway_client, managers=managers, runtime=runtime)

    name_service_routes.registry.members.clear()


def _replica_settings(replica_id: str, port: int) -> ReplicaSettings:
    return ReplicaSettings(
        replica_id=replica_id,
        replica_advertised_host=replica_id,
        replica_advertised_port=port,
        qdrant_url=f"http://qdrant-{replica_id[-1]}:6333",
        replica_peer_targets=(
            "replica-a=http://replica-a:8201,"
            "replica-b=http://replica-b:8202,"
            "replica-c=http://replica-c:8203"
        ),
        initial_token_replica_id="replica-a",
        semantic_score_threshold=0.18,
    )


def _build_replica_manager(settings: ReplicaSettings) -> ReplicaManager:
    embedder = DeterministicTestEmbedder(dimensions=settings.semantic_vector_size)
    vector_store = VectorStoreAdapter(
        settings=settings,
        client_factory=FakeQdrantClient,
        vector_size=embedder.vector_size,
    )
    cache_service = CacheService(
        settings=settings,
        vector_store=vector_store,
        embedder=embedder,
    )
    return ReplicaManager(
        settings=settings,
        cache_service=cache_service,
        name_service_client=NoOpAsyncNameServiceClient(),
        vector_store=vector_store,
        peer_client=ReplicaPeerClient(timeout_sec=2.0, transport=None),
    )


def _origin(url: str) -> str:
    parsed = httpx.URL(url)
    if parsed.port is None:
        return f"{parsed.scheme}://{parsed.host}"
    return f"{parsed.scheme}://{parsed.host}:{parsed.port}"
